# Generated by Django 3.2.4 on 2021-06-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answer_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='likes',
            new_name='verify',
        ),
    ]
