# Generated by Django 3.2.4 on 2021-06-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_rename_likes_answer_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='verify',
        ),
    ]
