# Generated by Django 3.2.2 on 2021-05-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ans_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
