# Generated by Django 3.2.3 on 2021-05-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210526_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
