# Generated by Django 3.2.3 on 2021-05-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_category_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
