# Generated by Django 3.2.3 on 2021-05-29 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0008_auto_20210526_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='category_name', to='question.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
