# Generated by Django 3.2.4 on 2021-06-11 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0012_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='qns_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
