# Generated by Django 3.2.4 on 2021-06-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_alter_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
