# Generated by Django 3.2.3 on 2021-05-20 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
