# Generated by Django 3.2.3 on 2021-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210524_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='category_name', to='question.Category'),
        ),
    ]
