# Generated by Django 3.2.3 on 2021-05-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20210526_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='question.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
