# Generated by Django 3.2.3 on 2021-05-29 07:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0009_auto_20210529_0322'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ans_cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('ans_description', models.TextField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.question')),
            ],
        ),
    ]
